### ISSUE TITLE
No Examples for the MilkV included in IDE

### ISSUE THREAD

**Issue by SensorsIot** [milkv-duo/duo-arduino#10]
I thought I followed your instructions, but I did not get any specific examples in my IDE (I tried both old and new). The title "Examples for the Duo Dev Module" is there, but they are greyed out.
I would like to create a video with this board. But without examples, it is not easy...

**Comment by shiptux** [comment]
Hi, could you please provide something more details, such as a picture, and your system information?

> I thought I followed your instructions, but I did not get any specific examples in my IDE (I tried both old and new). The title "Examples for the Duo Dev Module" is there, but they are greyed out. I would like to create a video with this board. But without examples, it is not easy...

**Comment by SensorsIot** [comment]
Yes, of course.
![MilkV](https://github.com/milkv-duo/duo-arduino/assets/13062557/eb0d0aa2-c1db-474b-8fa9-cba7d0068b97)

Here you see the details. I use Windows 11 with Arduino 2.3.2 and SG200X version 0.2.3. The selected module is the Duo Dev Module, and there are no example files visible

**Comment by shiptux** [comment]
The SG200x board doesn't have any built examples. If you want to find some SG200x Arduino examples, https://milkv.io/docs/duo/getting-started/arduino is a good place.
You may see SG200x examples like this.
![image](https://github.com/milkv-duo/duo-arduino/assets/22735550/ce4445db-fc33-48bf-88ba-3113c38fcb1b)
But this are actually the examples provided by Arduino itself. Including Arduino ethernet, and so on.

**Comment by SensorsIot** [comment]
In this video ( https://youtu.be/QOdZkn0MmYk?si=zLfwZzlbOeERjaeK ), the examples were in the IDE. This is why I asked. But I will try to continue with the ones you mentioned.

**Comment by SensorsIot** [comment]
I was now able to make most of the examples work. Unfortunately, I do not understand the idea behind the mailbox example. It would be cool if it would transfer sensor data from the Arduino to the Linux system...
I searched for the Examples you mentioned above (Ethernet till TFT). So far, I did not find them in the link you provided. As shown in my screenshot, my "Examples for Duo Dev Module" contains nothing.

**Comment by SensorsIot** [comment]
BTW: I hope you saw my video: https://youtu.be/SeExddxWdNs?si=12NxHeijFIZgUnjO

**Comment by shiptux** [comment]
> BTW: I hope you saw my video: https://youtu.be/SeExddxWdNs?si=12NxHeijFIZgUnjO

This is a useful and interesting video for MilkV Arduino. Thanks.

> I searched for the Examples you mentioned above (Ethernet till TFT). So far, I did not find them in the link you provided. As shown in my screenshot, my "Examples for Duo Dev Module" contains nothing.

It should contain nothing, Duo Dev Module doesn't provide any examples at this moment.

> I was now able to make most of the examples work. Unfortunately, I do not understand the idea behind the mailbox example. It would be cool if it would transfer sensor data from the Arduino to the Linux system...

The mailbox could both send and receive,  this works well on Linux and FreeRTos. But didn't work on Arduino now. Actually I got the message from Arduino and shown in dmesg, but the mailbox program didn't. Maybe we should send an interrupt from Arduino, or just a bug should fixed in the next version.
