### ISSUE TITLE
Any ETA for Duo S support?

### ISSUE THREAD

**Issue by platima** [milkv-duo/duo-arduino#18]
I get a LOT of questions about this!

Thanks

**Comment by shiptux** [comment]
> I get a LOT of questions about this!
> 
> Thanks

Try https://github.com/kubuds/sophgo-arduino/commits/sg200x-dev/. Most of the functions work fine.

**Comment by BoryaGames** [comment]
> > I get a LOT of questions about this!
> > Thanks
> 
> Try https://github.com/kubuds/sophgo-arduino/commits/sg200x-dev/. Most of the functions work fine.

Thanks, I wish I saw that earlier, it actually works great, gave it a star :)

**Comment by BoryaGames** [comment]
That link was added to [official docs](https://milkv.io/docs/duo/getting-started/arduino) and says that you need to compile for DuoS, also if you check latest v1.1.3 release, there's no "DuoS does not yet support arduino." anymore, so probaly this issue can be closed now.
