### ISSUE TITLE
I can't upload Arduino application for Milk-V Duo

### ISSUE THREAD

**Issue by tanklist** [milkv-duo/duo-arduino#8]
I installed the latest version of Arduion IDE, I burned the appropriate firmware for the Milk-V board and I try to follow the tutorial [Arduino tutorial](https://milkv.io/ru/docs/duo/getting-started/arduino). But on step "Upload sketch into the board" I've got a lot of errors:

`C:/Users/tankist/AppData/Local/Arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld.exe: C:/Users/tankist/AppData/Local/Arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/rv64imfd_zicsr/lp64d\libc_nano.a(libc_a-signalr.o): in function `_getpid_r':
signalr.c:(.text._getpid_r+0x0): warning: _getpid is not implemented and will always fail
C:/Users/tankist/AppData/Local/Arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld.exe: C:/Users/tankist/AppData/Local/Arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/rv64imfd_zicsr/lp64d\libc_nano.a(libc_a-signalr.o): in function `.L0 ':
signalr.c:(.text._kill_r+0x20): warning: _kill is not implemented and will always fail
Traceback (most recent call last):
  File "C:\Users\tankist\AppData\Local\Arduino15\packages\sophgo\tools\burntool_py\0.2/burntool.py", line 11, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'
Failed uploading: uploading error: exit status 1`

OS version is Windows 10 22H2, Arduino IDE 2.3.2.

Could anybody tell me what is wrong? I do everything as in tutorial.

**Comment by shiptux** [comment]
Hi @tanklist 

> C:/Users/tankist/AppData/Local/Arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld.exe: C:/Users/tankist/AppData/Local/Arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/rv64imfd_zicsr/lp64d\libc_nano.a(libc_a-signalr.o): in function _getpid_r': 

This is just a warning infomation.

> C:/Users/tankist/AppData/Local/Arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/rv64imfd_zicsr/lp64d\libc_nano.a(libc_a-signalr.o): in function .L0 ': signalr.c:(.text._kill_r+0x20): warning: _kill is not implemented and will always fail Traceback (most recent call last): File "C:\Users\tankist\AppData\Local\Arduino15\packages\sophgo\tools\burntool_py\0.2/burntool.py", line 11, in <module> import serial ModuleNotFoundError: No module named 'serial' Failed uploading: uploading error: exit status 1

This is actually the error infomation. It seems that your system doesn't have python library "serial", which required by the burntool.py. You can try this in your cmd: 

```
python
PS C:\Users\shipt\Documents> python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import serial
```
And it might print an error info like:

```
>>> import serial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'serial'
```

If so, you should install pyserial via pip:

```
 pip install pyserial
```

**Comment by tanklist** [comment]
Ok, I installed "serial" module and it imports fine now. But upload process still has a lot of ploblems:

```
burntool.py v0.3

upload firmware C:\Users\tankist\AppData\Local\Temp\arduino\sketches\55344D6FCEE8478FD5B0F4166328865A/Blink.ino.elf
Exception in thread Thread-1 (recv_date):
Traceback (most recent call last):
  File "C:\Users\tankist\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\tankist\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tankist\AppData\Local\Arduino15\packages\sophgo\tools\burntool_py\0.2/burntool.py", line 37, in recv_date
    while ser.inWaiting() > 0:
          ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'inWaiting'
Traceback (most recent call last):
  File "C:\Users\tankist\AppData\Local\Arduino15\packages\sophgo\tools\burntool_py\0.2/burntool.py", line 259, in <module>
    start(sys.argv[1:])
  File "C:\Users\tankist\AppData\Local\Arduino15\packages\sophgo\tools\burntool_py\0.2/burntool.py", line 256, in start
    ser.close()
    ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
serial err: module 'serial' has no attribute 'Serial'
error: 'NoneType' object has no attribute 'is_open'
connect failed...
Failed uploading: uploading error: exit status 1
```

**Comment by tanklist** [comment]
Now it works fine, thank you.
